Dashboard: Executive Scorecard
https://app.powerbi.com/groups/e7f5fd70-4e9e-4b03-9066-058f006d2baa/dashboards/b37e23cc-ab51-4bb4-84af-a8d72f816414?experience=power-bi

Monthly Load Count
https://app.powerbi.com/groups/e7f5fd70-4e9e-4b03-9066-058f006d2baa/reports/fd17d3b6-8d07-43f2-b203-56c1a446d5db/ReportSection8af597154adc77d04b7d?experience=power-bi

Graph Query:
let
    Source = Sql.Database("sql16", "DWS No Rep Data"),
    dbo_v_TotalLoads_SuesMonthlyReport = Source{[Schema="dbo",Item="v_TotalLoads_SuesMonthlyReport"]}[Data],
    #"Filtered Rows: Year <> null" = Table.SelectRows(dbo_v_TotalLoads_SuesMonthlyReport, each ([Year] <> null))
in
    #"Filtered Rows: Year <> null"

Table Query:
let
    Source = Sql.Database("sql16", "DWS No Rep Data"),
    dbo_v_TotalLoads_SuesMonthlyReport_Division = Source{[Schema="dbo",Item="v_TotalLoads_SuesMonthlyReport_Division"]}[Data],
    #"Filtered Rows: Year <> null" = Table.SelectRows(dbo_v_TotalLoads_SuesMonthlyReport_Division, each ([Year] <> null))
in
    #"Filtered Rows: Year <> null"

